# Generated by Django 3.0 on 2020-01-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('pid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('m_room', models.CharField(choices=[('S1', '上海1'), ('S2', '上海2')], default='S1', max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('m_date', models.CharField(max_length=10)),
                ('m_stime', models.TimeField()),
                ('m_etime', models.TimeField()),
                ('m_inteval', models.IntegerField()),
                ('m_mp', models.CharField(max_length=50)),
                ('m_mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
